export type StoreUnit = {
	id: string;
	name: string;
	city: string;
	state: string;
	addressLine1?: string;
	addressLine2?: string;
	neighborhood?: string;
	zipCode?: string;
	phone: string | number;
	whatsapp?: string | number;
	email: string;
	/** URL do Google Maps (ou similar) */
	mapUrl?: string;
	/** horários em texto livre */
	hours?: string;
    hoursWeekend?: string;
    imageUrl?: string;
};

export const STORES_DEFAULT_EMAIL = "atendimento@fastsistemasconstrutivos.com.br";
export const STORES_DEFAULT_PHONE: string = "5521992882282";
export const STORES_DEFAULT_IMAGE: string = "/others/loja-da-fast-sistemas-construtivos.png";

const STORES_DEFAULT_CONTACT = {
	email: STORES_DEFAULT_EMAIL,
	phone: STORES_DEFAULT_PHONE,
} satisfies Pick<StoreUnit, "email" | "phone">;

function normalizeStoreImageUrl(imageUrl?: string) {
	if (!imageUrl) return STORES_DEFAULT_IMAGE;
	// Hoje não existe `public/images/lojas`, então esses caminhos geram 404.
	// Deixa funcional usando placeholder real. Quando você criar imagens reais,
	// aponte o `imageUrl` para um path que exista em `public/`.
	if (imageUrl.startsWith("/images/lojas/")) return STORES_DEFAULT_IMAGE;
	return imageUrl;
}

const RAW_STORE_UNITS: Array<Omit<StoreUnit, "email" | "phone">> = [
	// Exemplo (troque/adicione suas unidades aqui)
	{
		id: "serra-es",
		name: "Serra - ES",
		city: "Serra",
		state: "ES",
        imageUrl: "/images/lojas/serra-es.jpg",
		addressLine1: "R. Vitória, 251 - Alterosas, Serra - ES, CEP 29167-027",
		neighborhood: "Alterosas",
		zipCode: "29167-027",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Vitória+251+Alterosas+Serra+ES+29167-027",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "recife-pe",
		name: "Recife - PE",
		city: "Recife",
		state: "PE",
        imageUrl: "/images/lojas/serra-es.jpg",
		addressLine1: "Av. Caxangá, 814A - Madalena, Recife - PE, CEP 50711-095",
		neighborhood: "Madalena",
		zipCode: "50711-095",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Caxangá+814A+Madalena+Recife+PE+50711-095",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "atibaia-sp",
		name: "Atibaia - SP",
		city: "Atibaia",
		state: "SP",
        imageUrl: "/images/lojas/serra-es.jpg",
		addressLine1: "Av. São João, 1661 - Parque das Nações, Atibaia - SP, CEP 12946-000",
		neighborhood: "Parque das Nações",
		zipCode: "12946-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+São+João+1661+Parque+das+Nações+Atibaia+SP+12946-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "goiania-go",
		name: "Goiânia - GO",
		city: "Goiânia",
		state: "GO",
        imageUrl: "/images/lojas/serra-es.jpg",
		addressLine1: "Av. Vera Cruz, 143, Quadra 14, Lote 08 - Jardim Guanabara, Goiânia - GO, CEP 74823-060",
		neighborhood: "Jardim Guanabara",
		zipCode: "74823-060",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Vera+Cruz+143+Jardim+Guanabara+Goiânia+GO+74823-060",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "rio-grande-do-sul-rs",
		name: "Rio Grande do Sul - RS",
		city: "Vacaria",
		state: "RS",
        imageUrl: "/images/lojas/serra-es.jpg",
		addressLine1: "R. Campos Sales, 248, Sala 201 - Centro, Vacaria - RS, CEP 95200-000",
		neighborhood: "Centro",
		zipCode: "95200-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Campos+Sales+248+Sala+201+Centro+Vacaria+RS+95200-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "maua-sp",
		name: "Mauá - SP",
		city: "Mauá",
		state: "SP",
        imageUrl: "/images/lojas/serra-es.jpg",
		addressLine1: "Av. da Saudade, 83 - Mauá - SP, CEP 09310-310",
		neighborhood: "Centro",
		zipCode: "09310-310",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+da+Saudade+83+Mauá+SP+09310-310",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "maringa-pr",
		name: "Maringá - PR",
		city: "Maringá",
		state: "PR",
        imageUrl: "/images/lojas/serra-es.jpg",
		addressLine1: "Av. Kakogawa, 1761 - Maringá - PR, CEP 87050-000",
		neighborhood: "Centro",
		zipCode: "87050-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Kakogawa+1761+Maringá+PR+87050-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "nova-iguacu-rj",
		name: "Nova Iguaçu - RJ",
		city: "Nova Iguaçu",
		state: "RJ",
        imageUrl: "/images/lojas/nova-iguacu-rj.jpg",
		addressLine1: "Rodovia Presidente Dutra, 14600 - Nova Iguaçu - RJ, CEP 26260-000",
		neighborhood: "Centro",
		zipCode: "26260-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Rodovia+Presidente+Dutra+14600+Nova+Iguaçu+RJ+26260-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "campos-dos-goytacazes-rj",
		name: "Campos dos Goytacazes - RJ",
		city: "Campos dos Goytacazes",
		state: "RJ",
        imageUrl: "/images/lojas/campos-dos-goytacazes-rj.jpg",
		addressLine1: "Av. Vinte e Oito de Março 455 - Campos dos Goytacazes - RJ, CEP 28015-230",
		neighborhood: "Centro",
		zipCode: "28015-230",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Vinte+e+Oito+de+Março+455+Campos+dos+Goytacazes+RJ+28015-230",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "macapa-ap",
		name: "Macapá - AP",
		city: "Macapá",
		state: "AP",
        imageUrl: "/images/lojas/macapa-ap.jpg",
		addressLine1: "R. Mato Grosso, 656 - Pacoval, Macapá - AP, CEP 68900-020",
		neighborhood: "Pacoval",
		zipCode: "68900-020",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Mato+Grosso+656+Pacoval+Macapá+AP+68900-020",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "bento-goncalves-rs",
		name: "Bento Gonçalves - RS",
		city: "Bento Gonçalves",
		state: "RS",
        imageUrl: "/images/lojas/bento-goncalves-rs.jpg",
		addressLine1: "Av. Nelson Carraro, 77 - Santo Antão, Bento Gonçalves - RS, CEP 95700-000",
		neighborhood: "Santo Antão",
		zipCode: "95700-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Nelson+Carraro+77+Santo+Antão+Bento+Gonçalves+RS+95700-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "sao-luis-ma",
		name: "São Luís - MA",
		city: "São Luís",
		state: "MA",
        imageUrl: "/images/lojas/sao-luis-ma.jpg",
		addressLine1: "Av. dos Holandeses / Conselheiro Hilton Rodrigues, 6 - Loteamento IPEM Calhau, São Luís - MA, CEP 65075-120",
		neighborhood: "Loteamento IPEM Calhau",
		zipCode: "65075-120",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+dos+Holandeses+Conselheiro+Hilton+Rodrigues+6+Loteamento+IPEM+Calhau+São+Luís+MA+65075-120",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "campo-verde-mt",
		name: "Campo Verde - MT",
		city: "Campo Verde",
		state: "MT",
        imageUrl: "/images/lojas/campo-verde-mt.jpg",
		addressLine1: "R. A1, 800 - Greenville II, Campo Verde - MT, CEP 78195-000",
		neighborhood: "Greenville II",
		zipCode: "78195-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+A1+800+Greenville+II+Campo+Verde+MT+78195-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "campo-grande-ms",
		name: "Campo Grande - MS",
		city: "Campo Grande",
		state: "MS",
        imageUrl: "/images/lojas/campo-grande-ms.jpg",
		addressLine1: "Av. Costa e Silva, 107 - Vila Progresso, Campo Grande - MS, CEP 79002-060",
		neighborhood: "Vila Progresso",
		zipCode: "79002-060",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Costa+e+Silva+107+Vila+Progresso+Campo+Grande+MS+79002-060",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "rio-verde-go",
		name: "Rio Verde - GO",
		city: "Rio Verde",
		state: "GO",
        imageUrl: "/images/lojas/rio-verde-go.jpg",
		addressLine1: "R. Bezerra de Meneses - S/N Quadra 73, Lote 01 - Rio Verde - GO, CEP 75901-970",
		neighborhood: "Centro",
		zipCode: "75901-970",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Bezerra+de+Meneses+S/N+Quadra+73+Lote+01+Rio+Verde+GO+75901-970",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "muriae-mg",
		name: "Muriaé - MG",
		city: "Muriaé",
		state: "MG",
        imageUrl: "/images/lojas/muriae-mg.jpg",
		addressLine1: "R. Presidente Getúlio Vargas, 412 - Barra, Muriaé - MG, CEP 36880-000",
		neighborhood: "Barra",
		zipCode: "36880-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R+Presidente+Getulio+Vargas+412+Barra+Muriaé+MG+36880-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "vitoria-da-conquista-ba",
		name: "Vitória da Conquista - BA",
		city: "Vitória da Conquista",
		state: "BA",
        imageUrl: "/images/lojas/vitoria-da-conquista-ba.jpg",
		addressLine1: "Av. Luís Eduardo Magalhães, Quadra 05 - Recreio, Vitória da Conquista - BA, CEP 45000-000",
		neighborhood: "Recreio",
		zipCode: "45000-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Luís+Eduardo+Magalhães+Quadra+05+Recreio+Vitória+da+Conquista+BA+45000-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "itabuna-ba",
		name: "Itabuna - BA",
		city: "Itabuna",
		state: "BA",
        imageUrl: "/images/lojas/itabuna-ba.jpg",
		addressLine1: "Av. José Soares Pinheiro, 2205 - Lomanto Júnior, Itabuna - BA, CEP 45600-000",
		neighborhood: "Lomanto Júnior",
		zipCode: "45600-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+José+Soares+Pinheiro+2205+Lomanto+Júnior+Itabuna+BA+45600-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "itabuna-ba",
		name: "Itabuna - BA",
		city: "Itabuna",
		state: "BA",
        imageUrl: "/images/lojas/itabuna-ba.jpg",
		addressLine1: "Av. José Soares Pinheiro, 2205 - Lomanto Júnior, Itabuna - BA, CEP 45600-000",
		neighborhood: "Lomanto Júnior",
		zipCode: "45600-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+José+Soares+Pinheiro+2205+Lomanto+Júnior+Itabuna+BA+45600-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "camacari-ba",
		name: "Camaçari - BA",
		city: "Camaçari",
		state: "BA",
        imageUrl: "/images/lojas/camacari-ba.jpg",
		addressLine1: "Condomínio Industrial Costa do Coqueiro, Estrada do Côco, KM 10, Galpão 08 - Abrantes, Camaçari - BA, CEP 42800-000",
		neighborhood: "Abrantes",
		zipCode: "42800-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Cond.+Ind.+Costa+do+Coqueiro+Estr.+do+Côco+KM10+Galpão+08+Abrantes+Camaçari+BA+42800-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "feira-de-santana-ba",
		name: "Feira de Santana - BA",
		city: "Feira de Santana",
		state: "BA",
        imageUrl: "/images/lojas/feira-de-santana-ba.jpg",
		addressLine1: "R. Caracol, 15 - Santo Antônio dos Prazeres, Feira de Santana - BA, CEP 44000-000",
		neighborhood: "Santo Antônio dos Prazeres",
		zipCode: "44000-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Caracol+15+Santo+Antônio+dos+Prazeres+Feira+de+Santana+BA+44000-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "fortaleza-ce",
		name: "Fortaleza - CE",
		city: "Fortaleza",
		state: "CE",
        imageUrl: "/images/lojas/fortaleza-ce.jpg",
		addressLine1: "Av. Prefeito Evandro Ayres de Moura, 1031 - Mondubim, Fortaleza - CE, CEP 60714-150",
		neighborhood: "Mondubim",
		zipCode: "60714-150",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Pref.+Evandro+Ayres+de+Moura+1031+Mondubim+Fortaleza+CE+60714-150",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "paragominas-pa",
		name: "Paragominas - PA",
		city: "Paragominas",
		state: "PA",
        imageUrl: "/images/lojas/paragominas-pa.jpg",
		addressLine1: "R. Hermes da Fonseca, 398 - Angelim, Paragominas - PA, CEP 68600-000",
		neighborhood: "Angelim",
		zipCode: "68600-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Hermes+da+Fonseca+398+Angelim+Paragominas+PA+68600-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "maceio-al",
		name: "Maceió - AL",
		city: "Maceió",
		state: "AL",
        imageUrl: "/images/lojas/maceio-al.jpg",
		addressLine1: "Av. Deputado Humberto Mendes, 246 - Jaraguá Maceió - AL, CEP 57020-120",
		neighborhood: "Jaraguá",
		zipCode: "57020-120",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Deputado+Humberto+Mendes+246+Jaraguá+Maceió+AL+57020-120",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "otacilio-costa-sc",
		name: "Otacílio Costa - SC",
		city: "Otacílio Costa",
		state: "SC",
        imageUrl: "/images/lojas/otacilio-costa-sc.jpg",
		addressLine1: "R. Joseph W. Schaller, 93 - Poço Rico, Otacílio Costa - SC, CEP 88680-000",
		neighborhood: "Poço Rico",
		zipCode: "88680-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Joseph+W.+Schaller+93+Poço+Rico+Otacílio+Costa+SC+88680-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "sao-gotardo-mg",
		name: "São Gotardo - MG",
		city: "São Gotardo",
		state: "MG",
        imageUrl: "/images/lojas/sao-gotardo-mg.jpg",
		addressLine1: "Av. Vereador Antônio Inácio da Silva, 441 - Taquaril, São Gotardo - MG, CEP 38780-000",
		neighborhood: "Taquaril",
		zipCode: "38780-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Vereador+Antônio+Inácio+da+Silva+441+Taquaril+São+Gotardo+MG+38780-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "juiz-de-fora-mg",
		name: "Juiz de Fora - MG",
		city: "Juiz de Fora",
		state: "MG",
        imageUrl: "/images/lojas/juiz-de-fora-mg.jpg",
		addressLine1: "Av. Doutor Simeão de Faria, 17 - Santa Cruz, Juiz de Fora - MG, CEP 36036-330",
		neighborhood: "Santa Cruz",
		zipCode: "36036-330",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Doutor+Simeão+de+Faria+17+Santa+Cruz+Juiz+de+Fora+MG+36036-330",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "patos-de-minas-mg",
		name: "Patos de Minas - MG",
		city: "Patos de Minas",
		state: "MG",
        imageUrl: "/images/lojas/patos-de-minas-mg.jpg",
		addressLine1: "Av. Presidente Tancredo Neves, 1179 - Ipanema, Patos de Minas - MG, CEP 38700-000",
		neighborhood: "Ipanema",
		zipCode: "38700-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Presidente+Tancredo+Neves+1179+Ipanema+Patos+de+Minas+MG+38700-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "linhares-es",
		name: "Linhares - ES",
		city: "Linhares",
		state: "ES",
        imageUrl: "/images/lojas/linhares-es.jpg",
		addressLine1: "Av. José Armani, 826 - Movelar, Linhares - ES, CEP 29900-000",
		neighborhood: "Movelar",
		zipCode: "29900-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+José+Armani+826+Movelar+Linhares+ES+29900-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "guarulhos-sp",
		name: "Guarulhos - SP",
		city: "Guarulhos",
		state: "SP",
        imageUrl: "/images/lojas/guarulhos-sp.jpg",
		addressLine1: "Av. Papa João Paulo I, 2145 - Jardim Cumbica, Guarulhos - SP, CEP 07090-000",
		neighborhood: "Jardim Cumbica",
		zipCode: "07090-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Papa+João+Paulo+I+2145+Jardim+Cumbica+Guarulhos+SP+07090-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "barra-mansa-rj",
		name: "Barra Mansa - RJ",
		city: "Barra Mansa",
		state: "RJ",
        imageUrl: "/images/lojas/barra-mansa-rj.jpg",
		addressLine1: "R. Major Eduardo Pereira da Costa Rangel, 115 - Verbo Divino, Barra Mansa - RJ, CEP 27323-120",
		neighborhood: "Verbo Divino",
		zipCode: "27323-120",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Major+Eduardo+Pereira+da+Costa+Rangel+115+Verbo+Divino+Barra+Mansa+RJ+27323-120",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "rio-das-ostras-rj",
		name: "Rio das Ostras - RJ",
		city: "Rio das Ostras",
		state: "RJ",
        imageUrl: "/images/lojas/rio-das-ostras-rj.jpg",
		addressLine1: "Av. Jane Maria Martins Figueira, 1508 - Quadra 82 - Lote 01, Jardim Marilea, Rio das Ostras - RJ, CEP 28890-000",
		neighborhood: "Jardim Marilea",
		zipCode: "28890-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Jane+Maria+Martins+Figueira+1508+Quadra+82+Lote+01+Jardim+Marilea+Rio+das+Ostras+RJ+28890-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "marica-rj",
		name: "Maricá - RJ",
		city: "Maricá",
		state: "RJ",
        imageUrl: "/images/lojas/marica-rj.jpg",
		addressLine1: "Rodovia Amaral Peixoto, KM 22 - Loja 01 - São José de Imbassai, Maricá - RJ, CEP 24932-360",
		neighborhood: "São José de Imbassai",
		zipCode: "24932-360",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Rodovia+Amaral+Peixoto+KM+22+Loja+01+São+José+de+Imbassai+Maricá+RJ+24932-360",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "cabo-frio-rj",
		name: "Cabo Frio - RJ",
		city: "Cabo Frio",
		state: "RJ",
        imageUrl: "/images/lojas/cabo-frio-rj.jpg",
		addressLine1: "RJ-140, 38, Loja 02 - Vinhateiro, São Pedro da Aldeia - RJ, CEP 28940-000",
		neighborhood: "Vinhateiro",
		zipCode: "28940-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=RJ-140+38+Loja+02+Vinhateiro+São+Pedro+da+Aldeia+RJ+28940-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "araR.ma-rj",
		name: "AraR.ma - RJ",
		city: "AraR.ma",
		state: "RJ",
        imageUrl: "/images/lojas/araR.ma-rj.jpg",
		addressLine1: "Rodovia Amaral Peixoto, 8970 - Coqueiral, AraR.ma - RJ, CEP 28970-000",
		neighborhood: "Coqueiral",
		zipCode: "28970-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Rodovia+Amaral+Peixoto+8970+Coqueiral+AraR.ma+RJ+28970-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "alcantara-rj",
		name: "Alcântara - RJ",
		city: "Alcântara",
		state: "RJ",
        imageUrl: "/images/lojas/alcantara-rj.jpg",
		addressLine1: "R. Plínio Casado, 30 - Alcantara, São Gonçalo - RJ, CEP 24415-020",
		neighborhood: "Alcântara",
		zipCode: "24415-020",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Plínio+Casado+30+Alcantara+São+Gonçalo+RJ+24415-020",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "freguesia-rj",
		name: "Freguesia - RJ",
		city: "Freguesia",
		state: "RJ",
        imageUrl: "/images/lojas/freguesia-rj.jpg",
		addressLine1: "R. Soldado Luiz Gonzaga, 166 Anil - Freguesia, Rio de Janeiro - RJ, CEP 22745-153",
		neighborhood: "Freguesia",
		zipCode: "22745-153",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Soldado+Luiz+Gonzaga+166+Anil+Freguesia+Rio+de+Janeiro+RJ+22745-153",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "curicica-rj",
		name: "Curicica - RJ",
		city: "Curicica",
		state: "RJ",
        imageUrl: "/images/lojas/curicica-rj.jpg",
		addressLine1: "Estrada dos Bandeirantes, 4643 - Curicica, Rio de Janeiro - RJ, CEP 22743-110",
		neighborhood: "Curicica",
		zipCode: "22743-110",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Estrada+dos+Bandeirantes+4643+Curicica+Rio+de+Janeiro+RJ+22743-110",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "nova-iguacu-rj",
		name: "Nova Iguaçu - RJ",
		city: "Nova Iguaçu",
		state: "RJ",
        imageUrl: "/images/lojas/nova-iguacu-rj.jpg",
		addressLine1: "Av. Abílio Augusto Távora, 623 - Jardim Alvorada, Nova Iguaçu - RJ, CEP 22743-110",
		neighborhood: "Nova Iguaçu",
		zipCode: "22743-110",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Abílio+Augusto+Távora+623+Jardim+Alvorada+Nova+Iguaçu+RJ+22743-110",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "caxias-jd-primavera-rj",
		name: "Caxias/JD Primavera - RJ",
		city: "Caxias/JD Primavera",
		state: "RJ",
        imageUrl: "/images/lojas/caxias-jd-primavera-rj.jpg",
		addressLine1: "Rodovia Washington Luíz, 13920 - Jardim Primavera, Duque de Caxias - RJ, CEP 25240-120",
		neighborhood: "Jardim Primavera",
		zipCode: "25240-120",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Rodovia+Washington+Luíz+13920+Jardim+Primavera+Duque+de+Caxias+RJ+25240-120",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "sao-joao-de-meriti-rj",
		name: "São João de Meriti - RJ",
		city: "São João de Meriti",
		state: "RJ",
        imageUrl: "/images/lojas/sao-joao-de-meriti-rj.jpg",
		addressLine1: "R. Trevo, 79 - Jardim Jose Bonifacio, São João de Meriti - RJ, CEP 25585-120",
		neighborhood: "Jardim Jose Bonifacio",
		zipCode: "25585-120",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Trevo+79+Jardim+Jose+Bonifacio+São+João+de+Meriti+RJ+25585-120",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "campo-grande-rj",
		name: "Campo Grande - RJ",
		city: "Campo Grande",
		state: "RJ",
        imageUrl: "/images/lojas/campo-grande-rj.jpg",
		addressLine1: "Av. Brasil, 29601 - Realengo, Rio de Janeiro - RJ, CEP 21730-230",
		neighborhood: "Realengo",
		zipCode: "21730-230",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Brasil+29601+Realengo+Rio+de+Janeiro+RJ+21730-230",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "centro-rj",
		name: "Centro - RJ",
		city: "Centro",
		state: "RJ",
        imageUrl: "/images/lojas/centro-rj.jpg",
		addressLine1: "R. Barão de Souza Félix, 3 - Centro, Rio de Janeiro - RJ, CEP 20010-020",
		neighborhood: "Centro",
		zipCode: "20010-020",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=R.+Barão+de+Souza+Félix+3+Centro+Rio+de+Janeiro+RJ+20010-020",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "bonsucesso-rj",
		name: "Bonsucesso - RJ",
		city: "Bonsucesso",
		state: "RJ",
        imageUrl: "/images/lojas/bonsucesso-rj.jpg",
		addressLine1: "Av. Brasil, 6281 - Bonsucesso, Rio de Janeiro - RJ, CEP 21040-000",
		neighborhood: "Bonsucesso",
		zipCode: "21040-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Brasil+6281+Bonsucesso+Rio+de+Janeiro+RJ+21040-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
	{
		id: "ramos-rj",
		name: "Ramos - RJ",
		city: "Ramos",
		state: "RJ",
        imageUrl: "/images/lojas/ramos-rj.jpg",
		addressLine1: "Av. Brasil, 7800 - Ramos, Rio de Janeiro - RJ, CEP 21040-000",
		neighborhood: "Ramos",
		zipCode: "21040-000",
		mapUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Brasil+7800+Ramos+Rio+de+Janeiro+RJ+21040-000",
		hours: "08h às 18h",
        hoursWeekend: "08h às 12h",
	},
];


export const STORE_UNITS: StoreUnit[] = RAW_STORE_UNITS.map((unit) => ({
	...STORES_DEFAULT_CONTACT,
	...unit,
	imageUrl: normalizeStoreImageUrl(unit.imageUrl),
}));

export default STORE_UNITS;
